### ISSUE TITLE
Checklist for alpha

### ISSUE THREAD

**Issue by chrswng** [oshwa/oshwa-certification#36]
**Index**
- [x] Header copy:
OSHWA Certification provides an easy and straightforward way for producers to indicate that their products meet a uniform and well-defined standard for open-source compliance, benefiting both creators and consumers.
- [x] Directory section title: "CERTIFIED OPEN SOURCE SOFTWARE PROJECTS"
- [x] Copy:
OSHWA Certification provides an easy and straightforward way for producers to indicate that their products meet a uniform and well-defined standard for open-source compliance, benefiting both creators and consumers. Certification also grants producers the ability to use the Open Source Hardware Certification logo on their product. 

**Process**
- [x] Certification elements copy:
These four elements are found in open source hardware projects. Click on any of the elements to skip directly to its learning module.
- [x] Reorder to Hardware, Software, Documentation, Branding
- [x] Get started button goes to Hardware learning module

**Learning modules**
- [x] Navigation: see mockups for now
- [x] Kill Commercialization section for now (do i just delete the content?)
- [x] Can we do a click off the panels and still allow clicking on the panel?

**List page**
- [x] Project name and Certification date are acting a little funny

**Project page**
- [x] Remove "V"
- [x] Add country, date and contact (need your help with design)
