### ISSUE TITLE
OSHWA checklist 1

### ISSUE THREAD

**Issue by chrswng** [oshwa/oshwa-certification#61]
**Basics page**
- [x] Last section should be "WHAT IS OSHWA CERTIFICATION?"

**Process page**
- [x] Parentheticals for each element:
Hardware (functional elements of the product)
Software (code, firmware, or software involved in the product's functionality)
Documentation (including design files, schematics, and instructions)
Branding (brand names, product names, logos, and product design)
- [x] Change certification logo image [see new version below]
- [x] Copy all in one section now, see mockup (uses summary field in contentful)

**Certification page**
- [x] Denny changing to use Contentful 

**Form**
- [x] OSHWA Contact Email Address remove parenthetical "(this address will be kept private and only used for official communicatiosn from OSHWA about your certification)" since in help text already
- [x] In project types Home Connection is supposed to be Home Construction
- [x] Project keywords help text
- [x] In last checkbox section link License Agreement to http://certificate.oshwa.org/license-agreement/
 - [x] Need additional links/placement

**Menu**
- [x] GET STARTED should go directly to the form (CERTIFY A PROJECT is fine)

**Learning modules**
- [x] Example modals "LEARN MORE ABOUT THIS PROJECT'S LICENSING" should open new so we don't lose place on back
- [x] New design on tags for exemplars
- [x] Swap image and description on spectrum items (i.e. title, description, then image) [Chris to also crop images better]

**Exemplar**
- [x] Change Project Website button to Project Profile button
- [x] New design on tags for exemplars
