### ISSUE TITLE
Checklist 2

### ISSUE THREAD

**Issue by chrswng** [oshwa/oshwa-certification#70]
Process
- [x] Parenthesis missing in Branding item in Introduction section
- [x] Inset bullets in Hardware checklist
- [x] Remove F-F-Fiddle from hardware examples (Contentful)
- [x] Add Test Stand and Spectrometer to software examples (Contentful)
- [x] Change "Learn Why" in Branding Examples to "Branding Information"

Exemplar
- [x] Update order of licenses (Hardware, Software, Documentation, Branding)
- [x] Update project types (Contentful)
