### ISSUE TITLE
Checklist 3

### ISSUE THREAD

**Issue by chrswng** [oshwa/oshwa-certification#82]
Update Index copy:
- [x] Header: OSHWA Certification provides an easy and straightforward way for producers to indicate that their products meet a uniform and well-defined standard for open-source compliance
- [x] Projects section: The Certified Projects Directory makes it easy to find certified open source hardware and to search by type of hardware, license, and country of origin.

Requirements page
- [x] Reduce font size for H3 (smaller than H2, maybe 1.4rem)

Exemplar/Examples
- [x] Add "No Software" to Public Lab Spectrometer example
- [x] Hardware license explanation for Public Lab Spectrometer (Michael in Contentful)

Learning modules
- [x] Add some padding in copy section before examples section

About
- [x] Add a credit for toaster image (Michael in Contentful)
- [x] Add a section for how to contact OSHWA for edits to profiles (Michael in Contentful)
